export const LECTURE_NOTES = `
EPE1303 Electromagnetic Fields and Waves
Knowledge Points of Electrostatics and Magnetostatic

Coulomb’s law describes the electrostatic force between stationary electric charges.
Electric flux density D equals permittivity ε multiplied by electric field intensity E: D = εE
Electric flux density D in electric field is referred to as Flux lines per unit area
Permittivity characterizes ε: a material’s response to an electric field and is also known as the dielectric constant. εr, ε0, ε= εr* ε0
Gauss’s law states that the total electric flux through a closed surface equals the total enclosed charge divided by the permittivity ε of free space.
Electric flux through a closed surface depends only on the charge enclosed within the surface.
Electric flux is positive when more field lines leave a closed surface and negative when more field lines enter the surface.
The capacitance of parallel plates is given by C = εA/d.

Uniform electric fields exist approximately between large parallel plates.
Impedance is defined as the ratio of voltage to current (Ohm’s Law: R=V/I).
Electrostatic fields are conservative fields; work done in a conservative field is independent of the path taken.
Electric potential difference equals the negative line integral of the electric field.
Electric potential decreases in the direction of the electric field.
Electric field intensity is defined as force per unit charge acting on a test charge (E=F/q).
Electric field lines indicate the direction of force on a positive test charge.
Electric field lines originate from positive charges and terminate on negative charges or at infinity.
The density of electric field lines represents the magnitude of the electric field; the field is stronger where the lines are closer together.

Electric field lines never intersect because the electric field has a unique direction at every point.
Potential difference is defined as the work done by an external agent in moving a unit positive charge between two points.
Voltage is another term for electric potential difference.
Electric potential energy depends on the position of a charge in an electric field.
Electric field lines are conceptual representations rather than physical objects.
An equipotential surface is a surface on which the electric potential is constant.
Equipotential surfaces are perpendicular to electric field lines.
Equipotential surfaces are closer together where the electric field is stronger.
No work is done when moving a charge along an equipotential surface.
Electric force is given by F = qE.
The superposition principle applies to electric fields.
The electric field of a point charge is radial and decreases with the square of distance.
Permittivity ε0 of free space is approximately 8.854 × 10⁻¹² F/m.

The divergence (or "outflow") of the electric flux density (D) from an infinite small point in space is equal to the volume charge density at that point. ∇ · D = ρv
The curl (or "rotation") of the static electric field (E) is zero everywhere. ∇ × E = 0
Electric flux measures how much electric field passes through a surface.
A capacitor is any arrangement of two conductors separated by a dielectric, designed specifically to store energy in the form of an electric field.
Magnetic fields are generated by moving charges or electric currents.
Magnetic force acts only on moving charges; if velocity is zero, the magnetic force is zero.
Parallel currents flowing in the same direction attract each other, whereas currents in opposite directions repel each other.
To determine the direction of the magnetic field produced by a current, use the right-hand grip rule.
To determine the direction of magnetic force on a current or moving charge, use either the right-hand cross-product rule or Fleming’s left-hand rule.
Capacitance represents the ability of a system to store electric charge.
Inductance represents the ability of a system to store magnetic energy.
Formula involved: R=V/I; F = qE; |V|=|Ed|;
`;
